name: Build merged PR changes on Ubuntu

on:
  push:
    branches:
      - master
      - next-release
      - release-stage
      - stage
      - ballerina-1.2.x
      - alpha-stage

jobs:
  ubuntu_push_build:
    name: Build merged PR changes
    runs-on: ubuntu-latest
    timeout-minutes: 75

    steps:
      - uses: actions/checkout@v2

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build and publish
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew build -x createJavadoc --max-workers=2 --scan
          ./gradlew publish
          find ~/.gradle/caches/ -name "*.lock" -type f -delete
      - name: Trigger Standard Library Module Builds
        run: |
          echo "Triggering stdlib module builds"
          curl --request \
          POST 'https://api.github.com/repos/ballerina-platform/ballerina-standard-library/dispatches' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "event_type": "ballerina-lang-push"
          }'
