name: Build merged PR changes on Ubuntu

on:
  push:
    branches:
      - master
      - next-release
      - release-stage
      - stage
      - ballerina-1.2.x
      - alpha-stage

jobs:
  ubuntu_push_build:
    name: Build merged PR changes
    runs-on: ubuntu-latest
    timeout-minutes: 75

    steps:
      - uses: actions/checkout@v2

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew build -x createJavadoc --max-workers=2 --scan
          find ~/.gradle/caches/ -name "*.lock" -type f -delete

      - name: Publish Jacoco Coverage artifact
        env:
          packageUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          packagePAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew publishCodeCovPublicationToGitHubPackagesRepository --max-workers=2 --scan --no-daemon
